- name: Install Elasticsearch Master Node
  hosts: Elasticsearch-Master-Nodes #inventory dosyasında verdiğimiz node ismi
  roles:
    - role: ansible-elasticsearch
  vars:
    es_heap_size: "1g"
    es_config:
      cluster.name: "Test-cluster"
      cluster.initial_master_nodes:
        - "Test-Master-Node"
      node.name: "Mpl-Prod-Master-Node"
      discovery.zen.ping.unicast.hosts: "172.26.83.178" #master node ip
      discovery.zen.minimum_master_nodes: 1
      http.port: 9200
      transport.tcp.port: 9300
      network.host: "0.0.0.0" #{{ansible_host}}
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: analysis-icu

- name: Install Elasticsearch Data Nodes
  hosts: Elasticsearch-Data-Nodes #inventory dosyasında verdiğimiz node ismi
  roles:
    - role: ansible-elasticsearch
  vars:
    es_heap_size: "1g"
    es_data_dirs:
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "Test-cluster"
      node.name: "Test-Data-Node"
      discovery.zen.ping.unicast.hosts: "172.26.83.178" #master node ip
      discovery.zen.minimum_master_nodes: 1
      http.port: 9200
      network.host: "0.0.0.0" #{{ansible_host}}
      transport.tcp.port: 9300
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_plugins:
      - plugin: analysis-icu